version: "2"
services:
    db:
        image: mysql
        container_name: database
        environment:
          MYSQL_DATABASE: 'db'
          # So you don't have to use root, but you can if you like
          MYSQL_USER: 'user'
          # You can use whatever password you like
          MYSQL_PASSWORD: 'dev' # temporary keys for development
          # Password for root access
          MYSQL_ROOT_PASSWORD: 'dev' # temporary keys for development
        external_links:
          - mysql:db
    client:
        image: node
        container_name: client_layer
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/app/client
        working_dir: /usr/src/app/client
        links:
            - "exp:exp"
        # depends_on:
        #   exp:
        #     condition: service_healthy
        command: bash -c "npm install && npm start"
    exp:
        image: node
        container_name: experience_layer
        restart: always
        ports:
            - "3001:3001"
        volumes:
            - ./experience_layer:/usr/src/app/experience_layer
        working_dir: /usr/src/app/experience_layer
        # depends_on:
        #   db:
        #     condition: service_healthy
        command: bash -c "npm install && npm run dev"